FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Extremo

Extremo is an API for fetching research related content (notes, commentaries, essays, etc)
produced by a researcher probably in the humanities.

# Extremo API Root [/]

This resource does not have any attributes. Instead it offers the initial API affordances.

## Retrieve the Entry Point [GET]

+ Response 200 (application/hal+json)

        {
            "_links": {
                "questions": { "href": "/notes" }
            }
        }

## Notes collection [/notes{?page}]

+ Parameters
    + page (optional, number, `1`) ... The page of questions to return

### List All Notes [GET]

+ Response 200 (application/hal+json)

        {
            "_links": {
                "self": { "href": "/notes" },
                "next": { "href": "/notes?page=2" }
            },
            "_embedded": {
                "notes": [
                    {
                        name: 'test.md',
                        sha: '559430b6bc52ab25846c528fbff56032162e2216',
                        rawsize: 95,
                        blob: '### This is a note\n\nIt doesn\'t have much in it yet. \nNow it has a bit more.\nAnd now even more.\n',
                        updated_at: 2016-12-05T16:04:25.000Z,
                        created_at: 2016-12-03T14:21:27.000Z,
                        history: [
                          { sha: '69c7df3ed6a50359d0c19df97b8c8ebe21dd2399',
                            date: 2016-12-05T16:04:25.000Z },
                          { sha: '188c1161743983a0199760385a55c6a7450dc6ba',
                            date: 2016-12-04T17:43:45.000Z },
                          { sha: 'd909ade91aae7970a34ba91e800493f9bac7d473',
                            date: 2016-12-03T14:21:27.000Z } ]
                    },
                    {
                        name: 'test2.md',
                        sha: '72fa01795e79e8c64bd1719cb2dcebd7f88a5082',
                        rawsize: 53,
                        blob: '### This is a note\n\nIt doesn\'t have much in it yet. \n',
                        updated_at: 2016-12-03T19:02:46.000Z,
                        created_at: 2016-12-03T19:02:46.000Z,
                        history:
                         [ { sha: '01113285f7f7f36394473f6820cd6ce6fd28dd13',
                             date: 2016-12-03T19:02:46.000Z } ]
                    }
                ]
            }
        }
